// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace SystemDefs 
{
	public enum SystemStates
	{
		STANDBY,
		CLIMBING,
		FALLING
	}

	public class CurrentState : MonoBehaviour{
		#region Singleton Constructors
		static CurrentState()
		{
		}
		
		CurrentState()
		{
			m_oCurrentState = SystemStates.STANDBY;
		}
		
		public static CurrentState Instance 
		{
			get 
			{
				if (_instance == null) 
				{
					_instance = new GameObject ("CurrentState").AddComponent<CurrentState>();
				}
				
				return _instance;
			}
		}
		#endregion

		private SystemStates m_oCurrentState;
		private static CurrentState _instance = null;


		public SystemStates GetCurrentState(){
			return m_oCurrentState;
		}
		public void SetCurrentState(SystemStates state){
			m_oCurrentState = state;
		}

	}
}

